feat: add getData method to dataObject. modify demo and test.
theNorstroem/FuroBaseComponents pull request #154
Opened 2021-01-27 09:49 UTC by f-zou

-  add getData method to dataObject. modify demo and test.
with this method the _base64 value can be got .

2021-01-27 14:57 UTC, maltenorstroem requested changes
Could you please check my comment?

2021-01-27 14:57 UTC, maltenorstroem commented on packages/furo-data/src/furo-data-object.js
> +    this.dispatchEvent(customEvent);
In my opinion, getData() should return a value. With the @-ƒ-get-data="--dataModelReceived(*._base64)" wire, we should be able to transmit the model (this.data).
For me, a function that only fires an event feels a bit strange.

2021-01-27 15:09 UTC, f-zou commented on packages/furo-data/src/furo-data-object.js
> +    this.dispatchEvent(customEvent);
this.data._value and this.data._base64 are siblings unter this.data. therefor here return the this.data. man can wire (--xxx(*._base64)). Otherwise we can only return this.data._base64 or this.data._value.

2021-01-27 15:20 UTC, maltenorstroem commented on packages/furo-data/src/furo-data-object.js
> +    this.dispatchEvent(customEvent);
```
getData(){
  return this.data;
}
```
Now you can do @-ƒ-get-data="--modelReceived(*._base64), --modelRaw"

2021-01-27 15:24 UTC, maltenorstroem commented on packages/furo-data/src/furo-data-object.js
> +    this.dispatchEvent(customEvent);
Is the dispatchEvent really necessary? If you are working with flowbased you can fetch the result with @-ƒ. If you are working with plain JS you will get the result immediately.

2021-01-27 15:25 UTC, f-zou commented on packages/furo-data/src/furo-data-object.js
> +    this.dispatchEvent(customEvent);
but it seems like a endlos loop..

2021-01-28 07:27 UTC, maltenorstroem approved these changes

2021-01-28 07:29 UTC, merged